[package]
name = "rust-scratche-blockchain"
version = "0.1.0"
authors = ["Arman <arman2riazi@gmail.com>"]
edition = "2018"

[lib]
name = "library_blockchain"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[features]
unstable-doc-cfg = []

[package.metadata.docs.rs]
features = ["unstable-doc-cfg"]

[dependencies]
doc-cfg = { version = "0.1" }
hex = "0.3.2"
crypto-hash = "0.3.3"
