[toolchain]
channel = "stable-x86_64-unknown-linux-gnu"
components = [ "rustfmt", "rustc-dev","clippy"]
targets = [ "x86_64-unknown-linux-gnu", "wasm32-unknown-unknown" ]
rustflags = [
"-C", "link-arg=-undefined",
"-C", "link-arg=dynamic_lookup",
]
