[package]
name = "utils"
version = "0.0.1"
authors = ["Arman <armanriyazi.github.io@gmail.com>"]
description = "A scratched blockchain implementation"
edition = "2021"
readme = "README.md"
license = "MIT"

[lib]
name = "library_utils"
path = "./lib.rs"
