[package]
name = "library_utils"
version = "0.0.2"
authors = ["Arman <armanriyazi.github.io@gmail.com>"]
description = "A native utils-remotly"
edition = "2021"
readme = "README.md"
license = "MIT"

[lib]
name = "library_utils"
path = "./lib.rs"
